services:
#    opt_equipements.example:
#        class: OPT\EquipementsBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]


    OPT_Equipements.entityService:
        class: OPT\EquipementsBundle\Services\entityService
        arguments: ['@doctrine.orm.entity_manager']
        