services:
#    opt_equipements.example:
#        class: OPT\EquipementsBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - { name: serializer.normalizer }

    OPT_Equipements.entityService:
        class: OPT\EquipementsBundle\Services\entityService
        arguments: ['@doctrine.orm.entity_manager']
        