<?php

namespace OPT\EquipementsBundle\Repository;

/**
 * ConstructeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConstructeurRepository extends \Doctrine\ORM\EntityRepository
{
}
