<?php

namespace OPT\EquipementsBundle\Repository;

/**
 * IdentificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdentificationRepository extends \Doctrine\ORM\EntityRepository
{
}
