<?php

namespace OPT\EquipementsBundle\Repository;

/**
 * linkTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class linkTestRepository extends \Doctrine\ORM\EntityRepository
{
}
