<?php

namespace OPT\EquipementsBundle\Repository;

/**
 * linkTest2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class linkTest2Repository extends \Doctrine\ORM\EntityRepository
{
}
